/*-------------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/

#if !defined(COCO_BITARRAY_H__)
#define COCO_BITARRAY_H__

namespace Coco {

class BitArray
{
public:
	BitArray(size_t length = 0, bool defaultValue = false);
	BitArray(BitArray const &copy);
	BitArray(BitArray &&tmp) noexcept;
	~BitArray();

	size_t getCount() const;

	bool Get(size_t index) const;
	void Set(size_t index, const bool value);
	void SetAll(const bool value);
	bool Equal(BitArray const &right) const;
	bool Overlaps(BitArray const &right) const;
	bool operator[](size_t index) const { return Get(index); };

	BitArray const &operator=(BitArray const &right);
	BitArray const &operator=(BitArray &&tmp);

	void Not();
	void And(BitArray const &value);
	void AndNot(BitArray const &value);
	void Or(BitArray const &value);
	void Xor(BitArray const &value);

	BitArray *Clone() const;

private:
	size_t Count;
	unsigned char* Data;
};

}

#endif // !defined(COCO_BITARRAY_H__)
