#!/bin/bash

#*****************************************************************************
# Copyright (c) 2011-2020, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*****************************************************************************
# wrapper script for GraphViz dot
#
# The script manipulates the layout direction of the class diagrams. Most
# class diagrams look better in top-down direction, but a few need to be in
# left-right direction. Other diagrams are untouched.
#*****************************************************************************

# The home of GraphViz dot can be passed into this script as environment variable.
# Try a default location if not passed in.
case $PLATFORM in
    macosx-x86*) ;;
    *)           if [ -z "${GRAPHVIZ_DOT_HOME+x}" -a -x /usr/bin/dot ]; then
                     GRAPHVIZ_DOT_HOME=/usr/bin
                 fi ;;
esac
if [ -z ${GRAPHVIZ_DOT_HOME+x} ]; then
    echo 'Error: $GRAPHVIZ_DOT_HOME is not set.'
    exit 1
fi
if [ ! -x ${GRAPHVIZ_DOT_HOME}/dot ]; then
    echo 'Error: $GRAPHVIZ_DOT_HOME/dot is not executable as expected for GraphViz dot.'
    exit 1
fi

PATH=$GRAPHVIZ_DOT_HOME:$PATH

FILENAME=$1

# Mac / Linux compatible sed -i handling
case $PLATFORM in
    macosx-x86*)        sed_i="-i .bak" ;;
    *)                  sed_i="-i.bak"  ;;
esac

# Remove all explicit line breaks and IIDs.
sed $sed_i 's/\\l//g;s/0x........, 0x...., 0x...., 0x.., 0x.., 0x.., 0x.., 0x.., 0x.., 0x.., 0x../\.\.\./g' $FILENAME
rm $FILENAME.bak

# Use alternate direction for some inheritance diagrams.
FILENAME_ONLY=${FILENAME##*/}
if [   $FILENAME_ONLY = classmi_1_1base_1_1IInterface__inherit__graph.dot \
  	-o $FILENAME_ONLY = classmi_1_1base_1_1Interface__declare__inherit__graph.dot ]; then
    DIRECTION=-Grankdir=LR
    # Add line break after "mi::base::Interface_declare< ...,", i.e., with explicit last argument.
    sed $sed_i 's/mi::base::Interface_declare\\< ...,/mi::base::Interface_declare\\<\\l ...,/g' $FILENAME
    rm $FILENAME.bak
else
  	DIRECTION=-Grankdir=TB
fi

# echo $DIRECTION $FILENAME
exec dot "$@" $DIRECTION
