#!/usr/bin/env python3
#*****************************************************************************
# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*****************************************************************************
#
# Embed a binary file as a C/C++ unsigned-char array in a generated header.
# Invoked from add_custom_command as:
#   python bin2c.py --input <file> --output <file.h> --symbol <name>
#
# Output:
#   static const unsigned char <SYMBOL>[]  = { ... };
#   static const size_t        <SYMBOL>_len = N;
#
# The array is NOT NUL-terminated; consumers needing a C string (e.g.
# cuLinkAddData with CU_JIT_INPUT_PTX) must append the terminator themselves
# (see render/baker/baker/baker_cuda_oss.cpp).

import argparse


def main():
    p = argparse.ArgumentParser(description="Embed a binary file as a C unsigned-char array.")
    p.add_argument("--input",   required=True, help="path to the input (binary) file")
    p.add_argument("--output",  required=True, help="path to the generated .h file")
    p.add_argument("--symbol",  required=True, help="base C identifier (array + _len)")
    p.add_argument("--columns", type=int, default=16, help="bytes per line")
    args = p.parse_args()

    with open(args.input, "rb") as f:
        # bytearray iterates as ints on both Python 2 and 3.
        data = bytearray(f.read())

    lines = []
    for i in range(0, len(data), args.columns):
        chunk = data[i:i + args.columns]
        lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    body = "\n".join(lines)

    with open(args.output, "w") as f:
        f.write("// Generated by bin2c.py - do not edit.\n")
        f.write("#pragma once\n")
        f.write("#include <cstddef>\n")
        f.write("static const unsigned char %s[] = {\n" % args.symbol)
        f.write(body + "\n")
        f.write("};\n")
        f.write("static const size_t %s_len = %d;\n" % (args.symbol, len(data)))


if __name__ == "__main__":
    main()
