/******************************************************************************
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of NVIDIA CORPORATION nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *****************************************************************************/

#include "pch.h"

#include "baker_cuda_oss.h"
#include "baker_kernel_oss_params.h"
#include "baker.h"

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

#include <mi/neuraylib/icanvas.h>
#include <mi/neuraylib/itile.h>
#include <mi/neuraylib/imdl_backend.h>
#include <mi/neuraylib/itransaction.h>

#include <base/data/db/i_db_access.h>
#include <base/data/db/i_db_tag.h>
#include <base/data/db/i_db_transaction.h>
#include <base/hal/time/i_time.h>
#include <base/lib/log/i_log_logger.h>
#include <base/system/main/access_module.h>
#include <base/system/main/i_module_id.h>
#include <io/image/image/i_image.h>
#include <io/image/image/i_image_mipmap.h>
#include <io/image/image/i_image_utilities.h>
#include <io/scene/dbimage/i_dbimage.h>
#include <io/scene/texture/i_texture.h>

#include <cuda.h>
#include <cuda_runtime.h>
#include <vector_types.h>

// The device-side texture runtime. Provides the texture PODs (Texture /
// Texture_desc / Tex_frame / Uv_grid) and the Texture_handler this file fills
// and uploads to the device.
#include "texture_support_cuda.h"

// Embedded PTX of the baker kernel (generated by bin2c.py at build time).
#include "baker_kernel_oss_ptx.h"

#define log_error(...)   MI::LOG::mod_log->error(M_BAKER, MI::LOG::Mod_log::C_MISC, __VA_ARGS__)
#define log_warning(...) MI::LOG::mod_log->warning(M_BAKER, MI::LOG::Mod_log::C_MISC, __VA_ARGS__)
#define log_debug(...)   MI::LOG::mod_log->debug(M_BAKER, MI::LOG::Mod_log::C_MISC, __VA_ARGS__)

namespace MI {
namespace BAKER {

namespace {

bool are_all_pixels_equal_host(
    const float4* pixels,
    size_t        count,
    unsigned      num_components)
{
    if (count == 0) return true;
    constexpr float eps = 1e-7f;
    const float4 first = pixels[0];
    for (size_t i = 1; i < count; ++i) {
        if (num_components >= 1 && fabsf(pixels[i].x - first.x) > eps) return false;
        if (num_components >= 2 && fabsf(pixels[i].y - first.y) > eps) return false;
        if (num_components >= 3 && fabsf(pixels[i].z - first.z) > eps) return false;
        if (num_components >= 4 && fabsf(pixels[i].w - first.w) > eps) return false;
    }
    return true;
}

// ----------------------------------------------------------------------------
// Scope guards for the CUDA resources used by one bake. They make every error
// path in bake_texture() a plain `return false` — all cleanup is implicit and
// runs in reverse declaration order.
// ----------------------------------------------------------------------------

// Owns one device allocation.
struct Scoped_dptr {
    Scoped_dptr() = default;
    ~Scoped_dptr() { if (p) cuMemFree(p); }
    Scoped_dptr(const Scoped_dptr&) = delete;
    Scoped_dptr& operator=(const Scoped_dptr&) = delete;

    CUdeviceptr p = 0;
};

// Owns a CUDA JIT link state. The state also owns the cubin returned by
// cuLinkComplete, so it must stay alive until cuModuleLoadDataEx has run.
struct Scoped_link_state {
    Scoped_link_state() = default;
    ~Scoped_link_state() { if (state) cuLinkDestroy(state); }
    Scoped_link_state(const Scoped_link_state&) = delete;
    Scoped_link_state& operator=(const Scoped_link_state&) = delete;

    CUlinkState state = nullptr;
};

// Owns a loaded CUDA module.
struct Scoped_module {
    Scoped_module() = default;
    ~Scoped_module() { if (handle) cuModuleUnload(handle); }
    Scoped_module(const Scoped_module&) = delete;
    Scoped_module& operator=(const Scoped_module&) = delete;

    CUmodule handle = nullptr;
};

// Owns the CUDA arrays and texture objects backing the uploaded textures.
// Texture objects are destroyed before the arrays they reference.
struct Scoped_tex_resources {
    Scoped_tex_resources() = default;
    ~Scoped_tex_resources() {
        for (cudaTextureObject_t t : tex_objects) cudaDestroyTextureObject(t);
        for (cudaArray_t a : arrays)              cudaFreeArray(a);
    }
    Scoped_tex_resources(const Scoped_tex_resources&) = delete;
    Scoped_tex_resources& operator=(const Scoped_tex_resources&) = delete;

    std::vector<cudaArray_t>         arrays;
    std::vector<cudaTextureObject_t> tex_objects;
};

// Allocates device memory into `out` and copies `bytes` from `src`.
bool gpu_dup(Scoped_dptr &out, const void *src, size_t bytes)
{
    if (cuMemAlloc(&out.p, bytes) != CUDA_SUCCESS) {
        out.p = 0;
        return false;
    }
    return cuMemcpyHtoD(out.p, src, bytes) == CUDA_SUCCESS;
}

// ----------------------------------------------------------------------------
// Texture upload
// ----------------------------------------------------------------------------

// Upload a single uv-tile mipmap (level 0) as a pair of CUDA texture objects.
// `effective_gamma` linearises the data (see note below). On a hard CUDA error
// returns false; for soft issues (no canvas / zero size) leaves `out` zeroed
// and returns true (so the tile reads back as black / invalid).
bool upload_tile_canvas(
    IMAGE::Image_module          *image_module,
    const mi::neuraylib::ICanvas *canvas_in,
    mi::Float32                   effective_gamma,
    Scoped_tex_resources         &res,
    Texture                      &out)
{
    out = Texture();
    if (!canvas_in) return true;

    const unsigned tex_w = canvas_in->get_resolution_x();
    const unsigned tex_h = canvas_in->get_resolution_y();
    if (tex_w == 0 || tex_h == 0) return true;

    // Convert to RGBA float. This is required, not just convenient: the
    // device side creates the cudaArray with a 4x32-bit-float channel
    // descriptor (see below) and every device lookup reads a float4, so the
    // host upload must be RGBA float32. The baker is not performance-critical,
    // so the four-channel cost over single/three-channel inputs is fine and
    // keeps every tile a uniform representation.
    mi::base::Handle<mi::neuraylib::ICanvas> rgba_canvas(
        image_module->convert_canvas(canvas_in, IMAGE::PT_COLOR));
    if (!rgba_canvas) return true;

    // Linearise. With tex_lookup_call_mode = "vtable" the MDL-emitted PTX
    // expects texture data to already be in linear color space — the
    // built-in CPU runtime handles this transparently, but the vtable
    // runtime in texture_support_cuda.h does NOT. If we skipped this the
    // GPU bake would come out brighter than the CPU bake for any sRGB or
    // gamma-2.2 input texture.
    if (effective_gamma > 0.0f && effective_gamma != 1.0f) {
        rgba_canvas->set_gamma(effective_gamma);
        image_module->adjust_gamma(rgba_canvas.get(), /*new_gamma=*/1.0f);
    }

    mi::base::Handle<const mi::neuraylib::ITile> tile(rgba_canvas->get_tile());
    const void* pixels = tile->get_data();

    cudaChannelFormatDesc fmt;
    fmt.x = 32; fmt.y = 32; fmt.z = 32; fmt.w = 32;
    fmt.f = cudaChannelFormatKindFloat;

    cudaArray_t array = nullptr;
    if (cudaMallocArray(&array, &fmt, tex_w, tex_h, 0) != cudaSuccess || !array) {
        log_debug("Baker_cuda_oss: cudaMallocArray failed.");
        return false;
    }
    res.arrays.push_back(array);
    const size_t row_bytes = (size_t)tex_w * 4u * sizeof(float);
    if (cudaMemcpy2DToArray(array, 0, 0, pixels, row_bytes, row_bytes, tex_h,
                                cudaMemcpyHostToDevice) != cudaSuccess) {
        log_debug("Baker_cuda_oss: cudaMemcpy2DToArray failed.");
        return false;
    }

    cudaResourceDesc res_desc = {};
    res_desc.resType = cudaResourceTypeArray;
    res_desc.res.array.array = array;

    cudaTextureDesc tdesc_f = {};
    tdesc_f.addressMode[0] = cudaAddressModeWrap;
    tdesc_f.addressMode[1] = cudaAddressModeWrap;
    tdesc_f.filterMode = cudaFilterModeLinear;
    tdesc_f.readMode = cudaReadModeElementType;
    tdesc_f.normalizedCoords = 1;

    if (cudaCreateTextureObject(&out.filtered_object, &res_desc, &tdesc_f, nullptr)
        != cudaSuccess) {
        log_debug("Baker_cuda_oss: cudaCreateTextureObject(filtered) failed.");
        return false;
    }
    res.tex_objects.push_back(out.filtered_object);

    cudaTextureDesc tdesc_u = tdesc_f;
    tdesc_u.filterMode = cudaFilterModePoint;
    tdesc_u.addressMode[0] = cudaAddressModeBorder;
    tdesc_u.addressMode[1] = cudaAddressModeBorder;
    tdesc_u.normalizedCoords = 0;
    if (cudaCreateTextureObject(&out.unfiltered_object, &res_desc, &tdesc_u, nullptr)
        != cudaSuccess) {
        log_debug("Baker_cuda_oss: cudaCreateTextureObject(unfiltered) failed.");
        return false;
    }
    res.tex_objects.push_back(out.unfiltered_object);

    out.size = make_uint3(tex_w, tex_h, 1u);
    out.inv_size = make_float3(1.0f / (float)tex_w, 1.0f / (float)tex_h, 1.0f);
    return true;
}

// Build the descriptor for a 2D MDL texture referenced by the target code at
// index `tex_idx`, uploading every animation frame and every uv-tile. Per-tile
// `Texture` entries are appended to `host_tiles` (their absolute index is
// recorded in the per-frame grid's tile_offset); per-frame `Tex_frame`
// entries are appended to `host_frames` (the desc's frame range starts at
// `out_frame_base`). The desc's `frames`/`tiles` device pointers are patched
// by the caller after the flat arrays are uploaded.
//
// Non-2D textures (3D, cube) produce an invalid descriptor (is_valid == 0) so
// material lookups against them return the MDL "invalid texture" sentinel.
// Returns false only on a hard CUDA error.
bool upload_one_texture(
    DB::Transaction                   *transaction,
    mi::neuraylib::ITarget_code const *target_code,
    mi::Size                           tex_idx,
    Scoped_tex_resources              &res,
    std::vector<Texture>              &host_tiles,
    std::vector<Tex_frame>            &host_frames,
    Texture_desc                      &out_desc,
    mi::Size                          &out_frame_base)
{
    std::memset(&out_desc, 0, sizeof(out_desc));
    out_desc.is_valid = 0;
    out_frame_base = host_frames.size();

    const mi::neuraylib::ITarget_code::Texture_shape shape =
        target_code->get_texture_shape(tex_idx);
    if (shape != mi::neuraylib::ITarget_code::Texture_shape_2d) {
        log_debug("Baker_cuda_oss: skipping non-2D texture at index %u "
                  "(shape=%d) — material lookup will return invalid.",
                  (unsigned)tex_idx, (int)shape);
        return true;
    }

    // Resolve the DB texture and its image.
    const char* db_name = target_code->get_texture(tex_idx);
    if (!db_name) return true;
    DB::Tag tag = transaction->name_to_tag(db_name);
    if (!tag) return true;
    if (transaction->get_class_id(tag) != TEXTURE::ID_TEXTURE) return true;
    DB::Access<TEXTURE::Texture> tex(tag, transaction);
    DB::Tag image_tag = tex->get_image();
    if (!image_tag) return true;
    DB::Access<DBIMAGE::Image> image(image_tag, transaction);

    SYSTEM::Access_module<IMAGE::Image_module> image_module(false);

    const bool     is_uvtile  = image->is_uvtile();
    const mi::Size num_frames = image->get_length();   // never zero
    if (num_frames == 0) return true;

    for (mi::Size f = 0; f < num_frames; ++f) {
        const mi::Size frame_number = image->get_frame_number(f);

        mi::Sint32 min_u = 0, min_v = 0, max_u = 0, max_v = 0;
        image->get_uvtile_uv_ranges(f, min_u, min_v, max_u, max_v);
        const mi::Uint32 count_u = (mi::Uint32)(max_u - min_u + 1);
        const mi::Uint32 count_v = (mi::Uint32)(max_v - min_v + 1);

        // Allocate (and zero) the bounding-rectangle grid for this frame.
        // Missing tiles stay zero -> read back as black on the device.
        const mi::Size grid_base = host_tiles.size();
        host_tiles.resize(grid_base + (size_t)count_u * count_v);

        const mi::Size n_tiles = image->get_frame_length(f);
        for (mi::Size i = 0; i < n_tiles; ++i) {
            mi::Sint32 u = 0, v = 0;
            if (image->get_uvtile_uv(f, i, u, v) != 0)
                continue;  // out-of-bounds uvtile id; leave slot black
            const mi::Size slot =
                (mi::Size)(v - min_v) * count_u + (mi::Size)(u - min_u);

            mi::base::Handle<const IMAGE::IMipmap> mipmap(
                image->get_mipmap(transaction, f, i));
            if (!mipmap) continue;
            mi::base::Handle<const mi::neuraylib::ICanvas> canvas(mipmap->get_level(0));

            const mi::Float32 gamma = tex->get_effective_gamma(transaction, f, i);
            if (!upload_tile_canvas(image_module.get(), canvas.get(), gamma,
                                    res, host_tiles[grid_base + slot]))
                return false;
        }

        Tex_frame fr;
        fr.frame_number   = (uint32_t)frame_number;
        fr.grid.min_u     = min_u;
        fr.grid.min_v     = min_v;
        fr.grid.count_u   = count_u;
        fr.grid.count_v   = count_v;
        fr.grid.tile_offset = (uint32_t)grid_base;
        host_frames.push_back(fr);
    }

    out_desc.is_valid    = 1;
    out_desc.is_uvtile   = is_uvtile ? 1u : 0u;
    out_desc.num_frames  = (uint32_t)num_frames;
    out_desc.first_frame = host_frames[out_frame_base].frame_number;
    out_desc.last_frame  = host_frames.back().frame_number;
    // frames / tiles device pointers are patched by the caller.
    return true;
}

// ----------------------------------------------------------------------------
// bake_texture() steps
// ----------------------------------------------------------------------------

// JIT-link the embedded baker kernel PTX with the MDL-generated PTX and load
// the result as a module.
bool link_and_load_module(
    mi::neuraylib::ITarget_code const *target_code,
    Scoped_module                     &out_module)
{
    TIME::Stopwatch sw_link;
    sw_link.start();

    Scoped_link_state link;
    if (cuLinkCreate(0, nullptr, nullptr, &link.state) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuLinkCreate failed.");
        return false;
    }

    // cuLinkAddData() treats CU_JIT_INPUT_PTX as a NUL-terminated C string and
    // scans past `size` until a NUL — so the data MUST be NUL-terminated and the
    // size must include the terminator. The embedded g_baker_kernel_oss_ptx[]
    // array (from bin2c.py) is NOT NUL-terminated, so pass a terminated copy
    // (size + 1). Without this, ptxas ingests whatever bytes follow the array in
    // memory and the JIT link fails.
    const std::string kernel_ptx(
        reinterpret_cast<const char*>(g_baker_kernel_oss_ptx),
        g_baker_kernel_oss_ptx_len);
    if (cuLinkAddData(
            link.state, CU_JIT_INPUT_PTX,
            (void*)kernel_ptx.c_str(), kernel_ptx.size() + 1,
            "baker_kernel_oss.ptx", 0, nullptr, nullptr) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuLinkAddData (kernel) failed.");
        return false;
    }
    if (cuLinkAddData(
            link.state, CU_JIT_INPUT_PTX,
            (void*)target_code->get_code(),
            target_code->get_code_size(),
            "mdl_lambda.ptx", 0, nullptr, nullptr) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuLinkAddData (MDL lambda) failed.");
        return false;
    }

    void*  cubin     = nullptr;
    size_t cubin_len = 0;
    if (cuLinkComplete(link.state, &cubin, &cubin_len) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuLinkComplete failed.");
        return false;
    }
    // `link` owns the cubin buffer, so the module is loaded before it goes
    // out of scope.
    if (cuModuleLoadDataEx(&out_module.handle, cubin, 0, nullptr, nullptr)
        != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuModuleLoadDataEx failed.");
        return false;
    }

    sw_link.stop();
    log_debug("Baker_cuda_oss linking time: %1.0f ms", sw_link.elapsed() * 1000);
    return true;
}

// Resolve the bake kernel entry point and the device address of the texture
// runtime's vtable. The kernel exposes a stable C-linkage pointer variable
// holding the address of tex_vtable — the unmangled name of `tex_vtable`
// itself depends on the C++ ABI, so the pointer indirection is reliable.
bool resolve_kernel(
    CUmodule      module,
    bool          is_environment,
    CUfunction   &out_bake,
    CUdeviceptr  &out_vtable)
{
    const char* entry = is_environment ? "bake_environment" : "bake_surface";
    if (cuModuleGetFunction(&out_bake, module, entry) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuModuleGetFunction(%s) failed.", entry);
        return false;
    }

    CUdeviceptr d_vtable_ptr_var = 0;
    size_t      vtable_ptr_var_size = 0;
    if (cuModuleGetGlobal(
            &d_vtable_ptr_var, &vtable_ptr_var_size, module,
            "baker_oss_tex_vtable_addr") != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuModuleGetGlobal(baker_oss_tex_vtable_addr) failed.");
        return false;
    }
    void* d_vtable_raw = nullptr;
    if (cuMemcpyDtoH(&d_vtable_raw, d_vtable_ptr_var, sizeof(void*))
        != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuMemcpyDtoH(vtable address) failed.");
        return false;
    }
    out_vtable = (CUdeviceptr)(uintptr_t)d_vtable_raw;
    return true;
}

// Upload every texture referenced by the target code — the per-texture
// descriptors plus the flat per-tile and per-frame arrays they point into —
// and the Texture_handler tying them together. Index 0 is the MDL "invalid
// texture" and carries no data.
bool upload_texture_handler(
    DB::Transaction                   *transaction,
    mi::neuraylib::ITarget_code const *target_code,
    CUdeviceptr                        d_vtable,
    Scoped_tex_resources              &res,
    Scoped_dptr                       &d_tiles,
    Scoped_dptr                       &d_frames,
    Scoped_dptr                       &d_descs,
    Scoped_dptr                       &d_handler)
{
    std::vector<Texture>      host_tiles;    // flat, absolute tile_offset
    std::vector<Tex_frame>    host_frames;   // flat, sliced per descriptor
    std::vector<Texture_desc> host_descs;
    std::vector<mi::Size>     desc_frame_base;
    const mi::Size num_tex = target_code->get_texture_count();
    if (num_tex > 1) {
        host_descs.reserve(num_tex - 1);
        desc_frame_base.reserve(num_tex - 1);
        for (mi::Size i = 1; i < num_tex; ++i) {
            Texture_desc desc;
            mi::Size frame_base = 0;
            if (!upload_one_texture(transaction, target_code, i, res,
                                    host_tiles, host_frames, desc, frame_base))
                return false;
            host_descs.push_back(desc);
            desc_frame_base.push_back(frame_base);
        }
    }

    if (!host_tiles.empty() &&
        !gpu_dup(d_tiles, host_tiles.data(), host_tiles.size() * sizeof(Texture)))
        return false;
    if (!host_frames.empty() &&
        !gpu_dup(d_frames, host_frames.data(), host_frames.size() * sizeof(Tex_frame)))
        return false;

    for (size_t k = 0; k < host_descs.size(); ++k) {
        // tile_offset values are absolute into host_tiles, so the global base
        // pointer is correct for every descriptor.
        host_descs[k].tiles  = (Texture const*)d_tiles.p;
        host_descs[k].frames = (Tex_frame const*)(
            d_frames.p + desc_frame_base[k] * sizeof(Tex_frame));
    }
    if (!host_descs.empty() &&
        !gpu_dup(d_descs, host_descs.data(), host_descs.size() * sizeof(Texture_desc)))
        return false;

    Texture_handler host_handler = {};
    host_handler.vtable        = reinterpret_cast<mi::neuraylib::Texture_handler_vtable const*>(d_vtable);
    host_handler.num_textures  = host_descs.size();
    host_handler.texture_descs = (Texture_desc const*)d_descs.p;
    host_handler.num_mbsdfs    = 0;
    host_handler.mbsdfs        = nullptr;
    host_handler.num_lightprofiles = 0;
    host_handler.lightprofiles     = nullptr;
    return gpu_dup(d_handler, &host_handler, sizeof(host_handler));
}

} // anonymous namespace


// ----------------------------------------------------------------------------
// Public methods
// ----------------------------------------------------------------------------

Baker_cuda_oss::Baker_cuda_oss(
    const Baker_module_impl           *baker_module,
    int                                dev_id,
    mi::neuraylib::ITarget_code const *target_code,
    mi::neuraylib::ICanvas            *texture,
    unsigned int                       samples,
    mi::Float32                        min_u,
    mi::Float32                        max_u,
    mi::Float32                        min_v,
    mi::Float32                        max_v,
    mi::Float32                        animation_time,
    float                             *constant_target,
    unsigned int                       constant_target_components,
    unsigned int                       state_flags,
    bool                               is_environment,
    bool                               want_constant_detection)
  : m_target_code(target_code, mi::base::DUP_INTERFACE),
    m_texture(texture, mi::base::DUP_INTERFACE),
    m_samples(samples),
    m_min_u(min_u),
    m_max_u(max_u),
    m_min_v(min_v),
    m_max_v(max_v),
    m_animation_time(animation_time),
    m_constant_target(constant_target),
    m_constant_target_components(constant_target_components),
    m_state_flags(state_flags),
    m_is_environment(is_environment),
    m_want_constant_detection(want_constant_detection)
{
    // Resolve / cache the per-device CUDA context. baker_module owns the
    // cache and the Cuda_dynload — we just push the context.
    CUcontext ctx = baker_module->get_dev_context_oss(dev_id);
    if (!ctx) {
        log_debug("Baker_cuda_oss: failed to obtain CUDA context.");
        return;
    }
    if (cuCtxPushCurrent(ctx) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuCtxPushCurrent failed.");
        return;
    }
    m_pushed_ctx = ctx;

    // Validate the device id before marking ready; the compute-capability
    // check was already performed by ensure_cuda_loaded_oss().
    CUdevice device = 0;
    if (cuDeviceGet(&device, dev_id) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuDeviceGet failed.");
        return;
    }
    m_ready = true;
}

Baker_cuda_oss::~Baker_cuda_oss()
{
    if (m_pushed_ctx) {
        CUcontext popped = nullptr;
        cuCtxPopCurrent(&popped);
    }
}

bool Baker_cuda_oss::bake_texture(DB::Transaction* transaction)
{
    if (!m_ready) return false;
    m_all_pixels_equal = false;

    // ---- Discover canvas geometry and pixel-type metadata ----
    unsigned tex_w = 1, tex_h = 1;
    unsigned n_components = m_constant_target_components;
    IMAGE::Pixel_type pixel_type = IMAGE::PT_UNDEF;
    mi::base::Handle<mi::neuraylib::ITile> tile;
    if (m_texture) {
        tex_w = m_texture->get_resolution_x();
        tex_h = m_texture->get_resolution_y();
        pixel_type = IMAGE::convert_pixel_type_string_to_enum(m_texture->get_type());
        if (pixel_type == IMAGE::PT_UNDEF) {
            log_debug("Baker_cuda_oss: unknown canvas pixel type.");
            return false;
        }
        if (pixel_type == IMAGE::PT_SINT8 || pixel_type == IMAGE::PT_RGBE
            || pixel_type == IMAGE::PT_FLOAT32) {
            n_components = 1;
        } else if (pixel_type == IMAGE::PT_FLOAT32_2) {
            n_components = 2;
        } else if (pixel_type == IMAGE::PT_FLOAT32_3 || pixel_type == IMAGE::PT_RGB_FP) {
            n_components = 3;
        } else if (pixel_type == IMAGE::PT_FLOAT32_4 || pixel_type == IMAGE::PT_COLOR) {
            n_components = 4;
        } else {
            // Results are written via ITile::set_pixel, which converts to any
            // canvas pixel type; n_components is only the constant-detection width.
            n_components = IMAGE::get_components_per_pixel(pixel_type);
        }
        tile = m_texture->get_tile();
    } else {
        pixel_type = IMAGE::PT_FLOAT32_4;  // unused; constant path writes raw floats
    }

    const float du = (float)(1.0 / (double)tex_w);
    const float dv = (float)(1.0 / (double)tex_h);

    // ---- Link kernel PTX + MDL PTX into a single module ----
    Scoped_module module;
    if (!link_and_load_module(m_target_code.get(), module))
        return false;

    // ---- Resolve kernel entry point and tex_vtable address ----
    CUfunction  f_bake   = nullptr;
    CUdeviceptr d_vtable = 0;
    if (!resolve_kernel(module.handle, m_is_environment, f_bake, d_vtable))
        return false;

    // ---- Upload textures (descriptors + flat per-tile / per-frame arrays) ----
    Scoped_tex_resources tex_res;
    Scoped_dptr d_tiles, d_frames, d_descs, d_handler;
    if (!upload_texture_handler(transaction, m_target_code.get(), d_vtable,
                                tex_res, d_tiles, d_frames, d_descs, d_handler))
        return false;

    // ---- Upload Bake_params_oss ----
    Bake_params_oss h_params = {
        tex_w, tex_h, m_samples, m_state_flags,
        (unsigned)(m_is_environment ? 1u : 0u),
        (unsigned)(pixel_type == IMAGE::PT_SINT8 ? 1u : 0u),
        du, dv, m_min_u, m_max_u, m_min_v, m_max_v,
        m_animation_time
    };
    Scoped_dptr d_params;
    if (!gpu_dup(d_params, &h_params, sizeof(h_params)))
        return false;

    // ---- Upload captured arguments (may be null) ----
    Scoped_dptr d_args;
    mi::base::Handle<const mi::neuraylib::ITarget_argument_block> args(
        m_target_code->get_argument_block(0));
    if (args && !gpu_dup(d_args, args->get_data(), args->get_size()))
        return false;

    // ---- Allocate result buffer (always float4 per pixel) ----
    const size_t pixel_count = (size_t)tex_w * (size_t)tex_h;
    const size_t result_bytes = pixel_count * sizeof(float4);
    Scoped_dptr d_results;
    if (cuMemAlloc(&d_results.p, result_bytes) != CUDA_SUCCESS)
        return false;

    // ---- Launch ----
    TIME::Stopwatch sw_kernel;
    sw_kernel.start();

    const unsigned int block_x = 16, block_y = 16;
    const unsigned int grid_x = (tex_w + block_x - 1) / block_x;
    const unsigned int grid_y = (tex_h + block_y - 1) / block_y;

    void* kernel_args[] = {
        &d_results.p,
        &d_params.p,
        &d_args.p,
        &d_handler.p
    };
    CUresult launch_res = cuLaunchKernel(
        f_bake,
        grid_x, grid_y, 1,
        block_x, block_y, 1,
        0, nullptr,
        kernel_args, nullptr);
    if (launch_res == CUDA_SUCCESS) {
        launch_res = cuStreamSynchronize(nullptr);
    }

    sw_kernel.stop();

    if (launch_res != CUDA_SUCCESS) {
        const char* err = nullptr;
        cuGetErrorString(launch_res, &err);
        log_debug("Baker_cuda_oss: kernel launch/sync failed: %s",
                  err ? err : "<unknown>");
        return false;
    }
    log_debug("Baker_cuda_oss execution time: %1.0f ms", sw_kernel.elapsed() * 1000);

    // ---- Read back and write canvas/constant target ----
    std::vector<float4> readback(pixel_count);
    if (cuMemcpyDtoH(readback.data(), d_results.p, result_bytes) != CUDA_SUCCESS) {
        log_debug("Baker_cuda_oss: cuMemcpyDtoH failed.");
        return false;
    }

    if (m_texture) {
        // Mirrors the CPU loop's per-pixel write in
        // Baker_fragmented_job::execute_fragment: scrub NaN, then hand the
        // cleaned floats to the canonical IMAGE encoder via ITile::set_pixel
        // (which handles RGBE/FLOAT*/COLOR conversion for us).
        auto clean = [](float v) { return (v != v) ? 0.0f : v; };
        for (size_t i = 0; i < pixel_count; ++i) {
            mi::Float32 v[4] = { clean(readback[i].x), clean(readback[i].y),
                                 clean(readback[i].z), clean(readback[i].w) };
            if (pixel_type == IMAGE::PT_SINT8) {
                // Majority-vote bool, encoded so set_pixel<PT_SINT8> yields
                // byte 1/0 (matches the CPU path in baker.cpp).
                const float bv = (v[0] > 0.5f) ? (1.0f / 255.0f) : 0.0f;
                v[0] = v[1] = v[2] = bv;
            }
            tile->set_pixel((mi::Uint32)(i % tex_w), (mi::Uint32)(i / tex_w), v);
        }
    } else {
        // Constant target: a single pixel of n_components floats.
        const float r[4] = {
            readback[0].x, readback[0].y, readback[0].z, readback[0].w
        };
        for (unsigned c = 0; c < m_constant_target_components; ++c)
            m_constant_target[c] = (r[c] != r[c]) ? 0.0f : r[c];
    }
    if (m_want_constant_detection) {
        m_all_pixels_equal = are_all_pixels_equal_host(
            readback.data(), pixel_count, n_components);
    }
    return true;
}

} // namespace BAKER
} // namespace MI
